In [56]:
import numpy as np
from copy import deepcopy
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [57]:
def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [58]:
def main():
    X = pd.read_csv('kmeans.csv',index_col=False)
    x1 = X['X1'].values
    x2 = X['X2'].values
    X = np.array(list(zip(x1,x2)))
    print(X)
    C_x = [6.2,6.6,6.5]
    C_y = [3.2,3.7,3.0]
    Centroid = np.array(list(zip(C_x,C_y)))
    print("Initial Centroids")
    print(Centroid.shape)
    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old)
    clusters = np.zeros(len(X))
    print(clusters)
    error = euclidean(Centroid,Centroid_old,None)
    print(error)
    iterr = 0
    k = 3
    while error != 0:
        iterr = iterr+1
        for i in range((len(X))):
            print(X[i])
            distances = euclidean(X[i],Centroid)
            print(distances)
            cluster = np.argmin(distances)
            print(cluster)
            clusters[i] = cluster
        print("Cluster ",clusters)
        Centroid_old = deepcopy(Centroid)
        
        for p in range(k):
            points = [X[j] for j in range(len(X)) if clusters[j] == p]
            print("points ",points)
            Centroid[p] = np.mean(points,axis=0)
        print("Centre of the clustersafter ",iterr,"Iteration \n",Centroid)
        error = euclidean(Centroid,Centroid_old,None)
        print("Error....",error)
            
        

In [59]:
if __name__ == "__main__":
    main()

[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]]
Initial Centroids
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.53714481052205
[5.9 3.2]
[0.3        0.86023253 0.63245553]
0
[4.6 2.9]
[1.62788206 2.15406592 1.90262976]
0
[6.2 2.8]
[0.4        0.98488578 0.36055513]
2
[4.7 3.2]
[1.5        1.96468827 1.81107703]
0
[5.5 4.2]
[1.22065556 1.2083046  1.56204994]
1
[5. 3.]
[1.21655251 1.74642492 1.5       ]
0
[4.9 3.1]
[1.30384048 1.80277564 1.60312195]
0
[6.7 3.1]
[0.50990195 0.60827625 0.2236068 ]
2
[5.1 3.8]
[1.25299641 1.50332964 1.61245155]
0
[6. 3.]
[0.28284271 0.92195445 0.5       ]
0
Cluster  [0. 0. 2. 0. 1. 0. 0. 2. 0. 0.]
points  [array([5.9, 3.2]), array([4.6, 2.9]), array([4.7, 3.2]), array([5., 3.]), array([4.9, 3.1]), array([5.1, 3.8]), array([6., 3.])]
points  [array([5.5, 4.2])]
points  [array([6.2, 2.8]), array([6.7, 3.1])]
Centre of the clustersafter  1 Iteration 
 [[5.17142857 3.17142857